### ISSUE TITLE
Server error 500 upon listing songs in an album

### ISSUE THREAD

**Issue by jameseh96** [koehlma/pygrooveshark#13]
after receiving an grooveshark.classes.album.Album object and attempting to get the songs iterator a server error 500 is thrown.

```
>>> import grooveshark
>>> client=grooveshark.Client()
>>> client.init()
>>> results=client.search("Good Morning Susie Soho", client.ALBUMS)
>>> album=results.next()
>>> album.songs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/grooveshark/classes/album.py", line 92, in songs
    self._connection.header('albumGetSongs'))[1]['songs']]
  File "/usr/lib/python2.7/site-packages/grooveshark/__init__.py", line 136, in request
    with contextlib.closing(self.urlopen(request)) as response:
  File "/usr/lib64/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error
>>> 

```

**Comment by camilonova** [comment]
@jameseh96 @mjk3979 Can be closed now?
