### ISSUE TITLE
Client connection doesn't work

### ISSUE THREAD

**Issue by aarondiazr** [koehlma/pygrooveshark#28]
Hi, I'm trying establish connection with init method, but seems broken!

```
>>> cliente.init()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/iron/EntornosVirtuales/wag/local/lib/python2.7/site-packages/grooveshark/__init__.py", line 186, in init
    self.connection.init()
  File "/home/iron/EntornosVirtuales/wag/local/lib/python2.7/site-packages/grooveshark/__init__.py", line 115, in init
    return self.init_token(), self.init_queue()
  File "/home/iron/EntornosVirtuales/wag/local/lib/python2.7/site-packages/grooveshark/__init__.py", line 121, in init_token
    self._get_token()
  File "/home/iron/EntornosVirtuales/wag/local/lib/python2.7/site-packages/grooveshark/__init__.py", line 99, in _get_token
    'client' : 'htmlshark'})[1]
  File "/home/iron/EntornosVirtuales/wag/local/lib/python2.7/site-packages/grooveshark/__init__.py", line 136, in request
    with contextlib.closing(self.urlopen(request)) as response:
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 110] Connection timed out>
```

**Comment by EpocDotFr** [comment]
Grooveshark was shut down on April 30, 2015.
